version: '3.7'

services:
  postgres:
    image: postgres:14.1-alpine3.14
    container_name: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'password'
    ports:
      - "5432:5432"
    restart: always
  app:
    build: .
    container_name: app
    image: app
    ports:
      - "3000:3000"
    depends_on:
      - postgres

volumes:
  data: