// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/Aegon95/mytheresa-product-api/internal/db/entity"
	mock "github.com/stretchr/testify/mock"
)

// DiscountRepository is an autogenerated mock type for the DiscountRepository type
type DiscountRepository struct {
	mock.Mock
}

// GetDiscounts provides a mock function with given fields: _a0
func (_m *DiscountRepository) GetDiscounts(_a0 context.Context) ([]entity.Discount, error) {
	ret := _m.Called(_a0)

	var r0 []entity.Discount
	if rf, ok := ret.Get(0).(func(context.Context) []entity.Discount); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Discount)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
