// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/Aegon95/mytheresa-product-api/internal/db/entity"
	mock "github.com/stretchr/testify/mock"
)

// ProductRepository is an autogenerated mock type for the ProductRepository type
type ProductRepository struct {
	mock.Mock
}

// GetProducts provides a mock function with given fields: _a0, _a1, _a2
func (_m *ProductRepository) GetProducts(_a0 context.Context, _a1 entity.Category, _a2 int64) ([]entity.Product, error) {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 []entity.Product
	if rf, ok := ret.Get(0).(func(context.Context, entity.Category, int64) []entity.Product); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Product)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, entity.Category, int64) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
